name: PromptExecutorMocked

on:
  workflow_dispatch:
  push:
    paths:
      - promptExecutor/**
jobs:
  prompt-test-mock-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./promptExecutor
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '22'
      - name: Deploy LLM Tool
        run: |
          yarn build-executor
        env:
          GITHUB_TOKEN: ${{ secrets.LLM_PROMPT_EXECUTOR_TOKEN }}
      - name: Launch Prompt Tests
        run: |
          yarn install
          yarn generate-in-context-learning-data
          yarn test-mock
